//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.24 at 11:57:52 AM ART 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://labs.zaubersoftware.com/ns/2011/05/gnip4j/activity", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.zaubersoftware.gnip4j.api.model;
